package aws

case class Region(value: String)

object Region {

  object Aws {
    val `af-south-1`     = Region("af-south-1")
    val `ap-east-1`      = Region("ap-east-1")
    val `ap-northeast-1` = Region("ap-northeast-1")
    val `ap-northeast-2` = Region("ap-northeast-2")
    val `ap-northeast-3` = Region("ap-northeast-3")
    val `ap-south-1`     = Region("ap-south-1")
    val `ap-south-2`     = Region("ap-south-2")
    val `ap-southeast-1` = Region("ap-southeast-1")
    val `ap-southeast-2` = Region("ap-southeast-2")
    val `ap-southeast-3` = Region("ap-southeast-3")
    val `ap-southeast-4` = Region("ap-southeast-4")
    val `ca-central-1`   = Region("ca-central-1")
    val `cn-north-1`     = Region("cn-north-1")
    val `cn-northwest-1` = Region("cn-northwest-1")
    val `eu-central-1`   = Region("eu-central-1")
    val `eu-central-2`   = Region("eu-central-2")
    val `eu-north-1`     = Region("eu-north-1")
    val `eu-south-1`     = Region("eu-south-1")
    val `eu-south-2`     = Region("eu-south-2")
    val `eu-west-1`      = Region("eu-west-1")
    val `eu-west-2`      = Region("eu-west-2")
    val `eu-west-3`      = Region("eu-west-3")
    val `il-central-1`   = Region("il-central-1")
    val `me-central-1`   = Region("me-central-1")
    val `me-south-1`     = Region("me-south-1")
    val `sa-east-1`      = Region("sa-east-1")
    val `us-east-1`      = Region("us-east-1")
    val `us-east-2`      = Region("us-east-2")
    val `us-gov-east-1`  = Region("us-gov-east-1")
    val `us-gov-west-1`  = Region("us-gov-west-1")
    val `us-west-1`      = Region("us-west-1")
    val `us-west-2`      = Region("us-west-2")
  }

  object Aliyun {
    val `ap-northeast-1`              = Region("ap-northeast-1")
    val `ap-northeast-2-pop`          = Region("ap-northeast-2-pop")
    val `ap-south-1`                  = Region("ap-south-1")
    val `ap-southeast-1`              = Region("ap-southeast-1")
    val `ap-southeast-2`              = Region("ap-southeast-2")
    val `ap-southeast-3`              = Region("ap-southeast-3")
    val `ap-southeast-5`              = Region("ap-southeast-5")
    val `cn-beijing`                  = Region("cn-beijing")
    val `cn-beijing-finance-1`        = Region("cn-beijing-finance-1")
    val `cn-beijing-finance-pop`      = Region("cn-beijing-finance-pop")
    val `cn-beijing-gov-1`            = Region("cn-beijing-gov-1")
    val `cn-beijing-nu16-b01`         = Region("cn-beijing-nu16-b01")
    val `cn-chengdu`                  = Region("cn-chengdu")
    val `cn-edge-1`                   = Region("cn-edge-1")
    val `cn-fujian`                   = Region("cn-fujian")
    val `cn-haidian-cm12-c01`         = Region("cn-haidian-cm12-c01")
    val `cn-hangzhou`                 = Region("cn-hangzhou")
    val `cn-hangzhou-bj-b01`          = Region("cn-hangzhou-bj-b01")
    val `cn-hangzhou-finance`         = Region("cn-hangzhou-finance")
    val `cn-hangzhou-internal-prod-1` = Region("cn-hangzhou-internal-prod-1")
    val `cn-hangzhou-internal-test-1` = Region("cn-hangzhou-internal-test-1")
    val `cn-hangzhou-internal-test-2` = Region("cn-hangzhou-internal-test-2")
    val `cn-hangzhou-internal-test-3` = Region("cn-hangzhou-internal-test-3")
    val `cn-hangzhou-test-306`        = Region("cn-hangzhou-test-306")
    val `cn-heyuan`                   = Region("cn-heyuan")
    val `cn-hongkong`                 = Region("cn-hongkong")
    val `cn-hongkong-finance-pop`     = Region("cn-hongkong-finance-pop")
    val `cn-huhehaote`                = Region("cn-huhehaote")
    val `cn-north-2-gov-1`            = Region("cn-north-2-gov-1")
    val `cn-qingdao`                  = Region("cn-qingdao")
    val `cn-qingdao-nebula`           = Region("cn-qingdao-nebula")
    val `cn-shanghai`                 = Region("cn-shanghai")
    val `cn-shanghai-et15-b01`        = Region("cn-shanghai-et15-b01")
    val `cn-shanghai-et2-b01`         = Region("cn-shanghai-et2-b01")
    val `cn-shanghai-finance-1`       = Region("cn-shanghai-finance-1")
    val `cn-shanghai-inner`           = Region("cn-shanghai-inner")
    val `cn-shanghai-internal-test-1` = Region("cn-shanghai-internal-test-1")
    val `cn-shenzhen`                 = Region("cn-shenzhen")
    val `cn-shenzhen-finance-1`       = Region("cn-shenzhen-finance-1")
    val `cn-shenzhen-inner`           = Region("cn-shenzhen-inner")
    val `cn-shenzhen-st4-d01`         = Region("cn-shenzhen-st4-d01")
    val `cn-shenzhen-su18-b01`        = Region("cn-shenzhen-su18-b01")
    val `cn-wuhan`                    = Region("cn-wuhan")
    val `cn-yushanfang`               = Region("cn-yushanfang")
    val `cn-zhangbei-na61-b01`        = Region("cn-zhangbei-na61-b01")
    val `cn-zhangjiakou`              = Region("cn-zhangjiakou")
    val `cn-zhangjiakou-na62-a01`     = Region("cn-zhangjiakou-na62-a01")
    val `cn-zhengzhou-nebula-1`       = Region("cn-zhengzhou-nebula-1")
    val `eu-central-1`                = Region("eu-central-1")
    val `eu-west-1`                   = Region("eu-west-1")
    val `eu-west-1-oxs`               = Region("eu-west-1-oxs")
    val `me-east-1`                   = Region("me-east-1")
    val `rus-west-1-pop`              = Region("rus-west-1-pop")
    val `us-east-1`                   = Region("us-east-1")
    val `us-west-1`                   = Region("us-west-1")
  }

  object Gcp {
    val `asia-east1`              = Region("asia-east1")
    val `asia-east2`              = Region("asia-east2")
    val `asia-northeast1`         = Region("asia-northeast1")
    val `asia-northeast2`         = Region("asia-northeast2")
    val `asia-northeast3`         = Region("asia-northeast3")
    val `asia-south1`             = Region("asia-south1")
    val `asia-south2`             = Region("asia-south2")
    val `asia-southeast1`         = Region("asia-southeast1")
    val `asia-southeast2`         = Region("asia-southeast2")
    val `australia-southeast1`    = Region("australia-southeast1")
    val `australia-southeast2`    = Region("australia-southeast2")
    val `europe-central2`         = Region("europe-central2")
    val `europe-north1`           = Region("europe-north1")
    val `europe-southwest1`       = Region("europe-southwest1")
    val `europe-west1`            = Region("europe-west1")
    val `europe-west2`            = Region("europe-west2")
    val `europe-west3`            = Region("europe-west3")
    val `europe-west4`            = Region("europe-west4")
    val `europe-west6`            = Region("europe-west6")
    val `europe-west8`            = Region("europe-west8")
    val `europe-west9`            = Region("europe-west9")
    val `northamerica-northeast1` = Region("northamerica-northeast1")
    val `northamerica-northeast2` = Region("northamerica-northeast2")
    val `southamerica-east1`      = Region("southamerica-east1")
    val `southamerica-west1`      = Region("southamerica-west1")
    val `us-central1`             = Region("us-central1")
    val `us-east1`                = Region("us-east1")
    val `us-east4`                = Region("us-east4")
    val `us-east5`                = Region("us-east5")
    val `us-west1`                = Region("us-west1")
    val `us-west2`                = Region("us-west2")
    val `us-west3`                = Region("us-west3")
    val `us-west4`                = Region("us-west4")

  }
}
